<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>exploration_manager</name>
  <version>1.0.0</version>
  <description>TODO: Package description</description>
  <maintainer email="alessio.deluca@iit.it">Alessio De Luca</maintainer>
  <license>TODO: License declaration</license>


  <buildtool_depend>ament_cmake</buildtool_depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <depend>rclcpp</depend>
  <depend>rclcpp_lifecycle</depend>

  <depend>std_msgs</depend>
  <depend>geometry_msgs</depend>
  <depend>sensor_msgs</depend>
  <depend>std_srvs</depend>
  <depend>exploration_manager_actions</depend>
  <depend>frontier_extraction_msgs</depend>
  <depend>frontier_extraction_srvs</depend>
  <depend>behaviortree_cpp</depend>
  <depend>tf2</depend>
  <depend>tf2_ros</depend>
  <depend>tf2_eigen</depend>
  <depend>nav2_msgs</depend>
  <depend>action_msgs</depend>
  <depend>actionlib_msgs</depend>
  <depend>exploration_manager_msgs</depend>
  <depend>define_inspection_goals_srvs</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>