<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypelocation="http://www.ros.org/schema/package_format3.xsd"?>
<package format="3">
  <name>rrtstar_octomap_planner</name>
  <version>0.1.0</version>
  <description>RRT* planner using OctoMap for collision checking and PX4 odometry</description>
  <maintainer email="you@example.com">you</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>px4_msgs</depend>
  <depend>nav_msgs</depend>
  <depend>geometry_msgs</depend>
  <depend>std_msgs</depend>
  <depend>sensor_msgs</depend>
  <depend>octomap_msgs</depend>
  <depend>octomap</depend>
  <depend>frontier_extraction_msgs</depend>
  <depend>frontier_extraction_srvs</depend>
  <depend>exploration_manager_msgs</depend>

  <!-- OMPL as a system dependency -->
  <depend>libompl-dev</depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>